swagger: '2.0'
info:
  description: ''
  version: 0.0.1
  title: CrosswordGn API
  termsOfService: ''
  contact:
    email: siavash.sadabadi@gmail.com
basePath: /v1
tags:
  - name: words
    description: Words operations
schemes:
  - http
  - https
paths:
  /words:
    get:
      tags:
        - words
      summary: List of all words
      description: Get a list of all words stored in database
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/wordSchema'
    post:
      tags:
        - words
      summary: Create a new word
      description: Create a new word according to the provided word object.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: document
          schema:
            $ref: '#/definitions/wordSchema'
      responses:
        '201':
          schema:
            $ref: '#/definitions/wordSchema'
          description: Created
          headers:
            location:
              type: string
              description: Url to new resource
  '/words/{id}':
    get:
      tags:
        - words
      summary: Get word by id
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/idInQuery'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/wordSchema'
    put:
      tags:
        - words
      summary: Update word
      description: Update word at specified URI
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/idInQuery'
        - in: body
          name: document
          schema:
            $ref: '#/definitions/wordSchema'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/wordSchema'
    delete:
      tags:
        - words
      summary: Delete word by id
      parameters:
        - $ref: '#/parameters/idInQuery'
      responses:
        '204':
          description: Deleted
definitions:
  wordSchema:
    type: object
    required:
      - value
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      value:
        type: string
      clues:
        description: List of clues associated with the word.
        type: array
        items:
          $ref: '#/definitions/clue'
  clue:
    type: object
    properties:
      id:
        type: integer
        format: int64
      value:
        type: string
      used:
        description: Indicates how many times a clue has been used.
        type: integer
        format: int64
parameters:
  idInQuery:
    name: id
    in: path
    description: ID of the word to fetch
    type: integer
    required: true
